### ISSUE TITLE
blank image generated in addition to the actual heatmap

### ISSUE THREAD

**Issue by igordot** [raivokolde/pheatmap#37]
I am using R notebook. This is my chunk:
```{r}
test = matrix(rnorm(200), 20, 10)
pheatmap::pheatmap(test)
```
I guess it's due to the way pheatmap generates the plot, but it actually generates a blank image in addition to the actual plot. 

Is there a way to get rid of that first image? I see it in the RStudio output and in the .nb.html file. If I knit to HTML, the blank plot is not there.

I also tried using the `silent` parameter with similar results:
```{r}
p = pheatmap::pheatmap(test, silent = TRUE)
plot(p$gtable)
```

However, if I split the same code into two chunks, there is only one image generated:
```{r}
p = pheatmap::pheatmap(test, silent = TRUE)
```
```{r}
plot(p$gtable)
```

Do you know why this is happening? Is there a way to resolve this?

**Comment by tuomastik** [comment]
I guess you posted the same issue on [Stack Overflow](https://stackoverflow.com/q/45024123/5524090) as well, which has an answer. However, I'm now encountering this same issue but with [`vdiffr`](https://github.com/lionel-/vdiffr) visual testing package instead of R notebook. The produced pheatmap plot apparently contains an extra page, because I'm receiving the following error when generating expected output figure with `vdiffr::validate_cases()`:

> message: svglite only supports one page

**Comment by igordot** [comment]
@tuomastik Stack Overflow has a helpful response, but it's more of a workaround and not really a complete solution. I still can't avoid a blank image without splitting code into two chunks. I like R notebooks for demo purposes, so it would be good to have the code as simple as possible. Adding a second chunk is arguably more awkward then having a blank image.

**Comment by tuomastik** [comment]
@igordot Totally agree. I just linked it here for future reference 👍

**Comment by drychkov** [comment]
Hi All,

I have the exact same issue. I don't like the solution to split into chunks, since it's splitting the code. 
For myself, I found a solution to modify pheatmap code locally through the function trace() as follows:

1. trace(pheatmap, edit=TRUE)
2. Remove grid.newpage() from the if statement "if (is.na(filename) & !silent) {...}" at the bottom.
3. put grid.newpage() right before  "gt = heatmap_motor(...)" above this if statement
4. Save

It works well for R notebook, but changes remain only in your environment. Would love to have a permanent fix for the package, instead of doing it manually every time.

**Comment by jdreyf** [comment]
I posted a solution using the `filename` parameter on stack overflow: https://stackoverflow.com/questions/45024123/r-notebook-generates-a-blank-plot-in-addition-to-actual-plot/50279651

**Comment by igordot** [comment]
I am not sure that is solving the same problem. If you save as file, the plot is not in the notebook.

**Comment by jdreyf** [comment]
You're right, but it's a similar problem, potentially with the same cause, since calling `pheatmap` without the `filename` parameter prints an initial blank page in both situations.

**Comment by igordot** [comment]
Anything helps. This issue has been around for almost a year now. Whatever the solution is, it's not trivial.

**Comment by raivokolde** [comment]
It was a tricky issue as it was hard to pin down where exactly it happened. Thats why I had not figured out how to solve it before. Fortunately, I found an issue in ggplot2 that described a similar problem and contained some ideas how to fix it. 

Anyhow, the problem was related to sizing the different plot elements. When calculating the dimensions pheatmap has to figure out the size of all plot elements. For most it can do it without problem, but some like text size need an open graphics device to make the calculation. So to make the calculation it opens a new page that shows up in the notebooks.  

I do not know which command triggered the blank page, but the fix was to open a pdf connection to nowhere where the calculations can be done. As far as I can test it, it seems to fix the issue. 

Thanks guys keeping this issue open! I know its pretty frustrating behavior when using the R notebooks. I have taken a few stabs at it before, but could not figure out how to solve the issue. Hopefully, now its better, I'm just in the process of submitting the new version to CRAN.

**Comment by drychkov** [comment]
Thanks @raivokolde for fixing the issue! This all sounds very complicated. But not clear why the simple solution to move grid.newpage() just above "gt = heatmap_motor(...)" in the code could not be used? I did not get any problems with plotting when I was modifying the code this way.

**Comment by ning-y** [comment]
I still get the same error on version 1.0.12. I've checked that the fix described by @raivokolde (`pdf(file=NULL)`) is in the instance of the pheatmap function I used by checking `traceback(pheatmap, edit=TRUE)`.

The exact error message is
```
Error in grid.newpage() : svglite only supports one page 
```

The traceback ends at
```
5. stop(structure(list(message = "svglite only supports one page",
      call = grid.newpage(), cppstack = NULL), class = c("Rcpp::exception",
   "C++Error", "error", "condition")))
4. grid.newpage() 
3. (function (mat, color = colorRampPalette(rev(brewer.pal(n = 7, 
      name = "RdYlBu")))(100), kmeans_k = NA, breaks = NA, border_color = "grey60", 
      cellwidth = NA, cellheight = NA, scale = "none", cluster_rows = TRUE, 
      cluster_cols = TRUE, clustering_distance_rows = "euclidean",  ... 
2. do.call(pheatmap, arguments) at plotting.R#261
```

I am using RStudio 1.2.1335 with R 3.6.0 (svn 76424).
